class I18N:
    def __init__(self, language):
        if language == "en":
            self.load_text_in_english()
        elif language == "tr":
            self.load_text_in_chinese()
        else:
            raise NotImplementedError("Unsupported language.")

    def load_text_in_english(self):
        self.reservationid_heading = "Reservation ID"
        self.username_heading = "Username"
        self.country_heading = "Country"
        self.city_heading = "City"
        self.numberofpeople_heading = "Number of People"
        self.numberofroom_heading = "Number of Room"
        self.view_heading = "Room View"
        self.breakfast_heading = "Breakfast"
        self.ac_heading = "Air Conditioning"
        self.rs_heading = "Room service"
        self.reservationdate_heading = "Reservation Date"
        self.start_day_heading = "Check-in Day"
        self.finish_day_heading = "Check-out Day"
        self.welcome = "Welcome!"
        self.homepage = "Home Page"
        self.options_main = "Options"
        self.thanks = "Thank You!"
        self.history = "History"
        self.name = "Name:"
        self.surname= "Surname:"
        self.pno = "Phone Number:"
        self.username = "Username:"
        self.password = "Password:"
        self.rpassword = "Password(repeat):"
        self.reservation = "Reservation"
        self.new_reservation = "New Reservation"
        self.reservation_history = "Reservation History"
        self.country = "Country:"
        self.city = "City:"
        self.people = "Number Of People:"
        self.room = "Number Of Room:"
        self.room_type = "Room Type:"
        self.selected_view = "Selected View:"
        self.selected_options = "Selected option(s):"
        self.yes = "Yes"
        self.no = "No"
        self.options = "Options:"
        self.city_view = "City View"
        self.sea_view = "Sea View"
        self.nature_view = "Nature View"
        self.breakfast = "Breakfast"
        self.ac = "Air Conditioning"
        self.rs = "Room Service"
        self.notspecified = "Not Specified"
        self.start_day = "Check-in Day:"
        self.finish_day = "Check-out Day:"
        self.successful = "Your reservation is successful!"
        self.informations = "Your informations are:"
        self.reservationid = "Your reservation id:"
        self.login = "Login"
        self.signup = "Signup"
        self.back = "Back"
        self.signout= "Sign Out"
        self.complete = "Complete Reservation"
        self.elipor = "Welcome to ELIPOR HOTEL reservation system!"
        self.return_homepage = "Return Homepage"
        self.countryList = {'Select': ['Select'],
            'Turkey': ['Select', 'İstanbul', 'Ankara', 'Antalya'],
                        'England': ['Select', 'London', 'Manchester', 'Liverpool'],
                        'Italy': ['Select', 'Venice', 'Rome', 'Milan'],
                        'Netherlands': ['Select', 'Amsterdam', 'Rotterdam', 'Haarlem'],
                        'Spain': ['Select', 'Madrid', 'Barcelona', 'Valencia']}
        self.select = "Select"
        self.home_elipor = "ELIPOR HOTEL"
        self.info1 = "Welcome!"
        self.info2 = "Elipor Hotel has hotels in 5 different countries.\nWhich are; Turkey, England, Italy, Netherlands and Spain!\n" \
                     "You can also select from various cties including Istanbul, Amsterdam, Venice and London!\n" \
                     "\nOur system offers various options for your stay in Elipor Hotel." \
                     "\nYou can easily select if you would like to have breakfast included, or air conditioning option included in your room during your stay!"
        self.info3 = "\nSelect MAKE NEW RESERVATION from the menu above to fill up the form.\nSelect RESERVATION HISTORY button to see your previous reservations."
        self.lang_select_note = "Press F2 for Chinese (中文)"
        self.error = "Error"
        self.name_error = "Name must be entered:\n- at least 2 characters,\n- at most 20 characters must be entered."
        self.surname_error = "Surname must be entered:\n- at least 2 characters,\n- at most 20 characters must be entered."
        self.pNo_error = "Phone number must be entered:\n- at least 9 digits should be eneterd."
        self.username_error = "Username must be entered:\n- at least 5 characters or digits should be eneterd,\n- only . - _ can be used."
        self.password_error = "Password must be entered:\n- at least 7 characters or digits should be eneterd,\n- at least one capital letter,\n" \
                              "- at least one lower case letter and,\n- at least one number must be entered."
        self.price_label = "You can pay your visit while checking out!"
        self.delete = "To erase your reservation: While reservation you want to delete is selected press DEL key."
        self.mismatched = "Username and password mismatched."
        self.password_mismatched = "Passwords are not matching"
        self.username_exist = "Username is already exists in database. Please enter different one."
        self.country_error = "Country must be selected"
        self.city_error = "City must be selected"
        self.no_of_people_error = "Number of people must be selected"
        self.no_of_room_error = "Number of room must be selected"
        self.date_error = "Please select a valid date."
        self.delete_reservation = "Delete Reservation"
        self.are_you_sure = "Your reservation will be canceled. Are you sure?"
        self.are_you_sure_2 = "Are you sure?"

    def load_text_in_chinese(self):
        self.reservationid_heading = "预订编号"
        self.username_heading = "用户名"
        self.country_heading = "国家"
        self.city_heading = "城市"
        self.numberofpeople_heading = "人数"
        self.numberofroom_heading = "房间数"
        self.view_heading = "房间景观"
        self.breakfast_heading = "早餐"
        self.ac_heading = "空调"
        self.rs_heading = "客房服务"
        self.reservationdate_heading = "预订日期"
        self.start_day_heading = "入住日期"
        self.finish_day_heading = "退房日期"
        self.welcome = "欢迎!"
        self.homepage = "主页"
        self.options_main = "选项"
        self.thanks = "谢谢!"
        self.history = "历史记录"
        self.name = "姓名:"
        self.surname= "姓氏:"
        self.pno = "电话号码:"
        self.username = "用户名:"
        self.password = "密码:"
        self.rpassword = "密码(重复):"
        self.reservation = "预订"
        self.new_reservation = "新预订"
        self.reservation_history = "预订历史"
        self.country = "国家:"
        self.city = "城市:"
        self.people = "人数:"
        self.room = "房间数:"
        self.room_type = "房间类型:"
        self.selected_view = "选择的景观:"
        self.selected_options = "选择的选项:"
        self.yes = "是"
        self.no = "否"
        self.options = "选项:"
        self.city_view = "城市景观"
        self.sea_view = "海景"
        self.nature_view = "自然景观"
        self.breakfast = "早餐"
        self.ac = "空调"
        self.rs = "客房服务"
        self.notspecified = "未指定"
        self.start_day = "入住日期:"
        self.finish_day = "退房日期:"
        self.successful = "您的预订已成功!"
        self.informations = "您的信息:"
        self.reservationid = "您的预订编号:"
        self.login = "登录"
        self.signup = "注册"
        self.elipor = "欢迎来到ELIPOR酒店预订系统!"
        self.back = "返回"
        self.signout= "退出"
        self.complete = "完成预订"
        self.return_homepage = "返回主页"
        self.countryList = {'请选择': ['请选择'],
                        '中国': ['请选择', '北京', '上海', '广州'],
                        '土耳其': ['请选择', '伊斯坦布尔', '安卡拉', '安塔利亚'],
                        '英国': ['请选择', '伦敦', '曼彻斯特', '利物浦'],
                        '意大利': ['请选择', '威尼斯', '罗马', '米兰'],
                        '荷兰': ['请选择', '阿姆斯特丹', '鹿特丹', '哈勒姆'],
                        '西班牙': ['请选择', '马德里', '巴塞罗那', '瓦伦西亚']}
        self.select = "请选择"
        self.home_elipor = "ELIPOR酒店"
        self.info1 = "欢迎!"
        self.info2 = "Elipor酒店在5个不同的国家设有分店。\n包括中国、土耳其、英国、意大利和荷兰!\n" \
                     "您可以选择包括北京、伊斯坦布尔、威尼斯和伦敦在内的多个城市!\n" \
                     "\n我们的系统为您在Elipor酒店的住宿提供各种选择。" \
                     "\n您可以轻松选择是否需要在住宿期间包含早餐或空调选项!"
        self.info3 = "\n从上方菜单中选择'新预订'填写表格。\n选择'预订历史'按钮查看您之前的预订记录。"
        self.lang_select_note = "For English press F1 (英文按F1)"
        self.error = "错误"
        self.name_error = "必须输入姓名:\n- 至少2个字符,\n- 最多20个字符。"
        self.surname_error = "必须输入姓氏:\n- 至少2个字符,\n- 最多20个字符。"
        self.pNo_error = "必须输入电话号码:\n- 至少9位数字。"
        self.username_error = "必须输入用户名:\n- 至少5个字符或数字,\n- 只能使用 . - _ 符号。"
        self.password_error = "必须输入密码:\n- 至少7个字符或数字,\n- 至少一个大写字母,\n" \
                              "- 至少一个小写字母,\n- 至少一个数字。"
        self.price_label = "您可以在退房时支付费用!"
        self.delete = "要删除预订: 选择要删除的预订后按DEL键。"
        self.mismatched = "用户名和密码不匹配。"
        self.password_mismatched = "密码不匹配"
        self.username_exist = "用户名已存在。请输入不同的用户名。"
        self.country_error = "必须选择国家"
        self.city_error = "必须选择城市"
        self.no_of_people_error = "必须选择人数"
        self.no_of_room_error = "必须选择房间数"
        self.date_error = "请选择有效日期。"
        self.delete_reservation = "删除预订"
        self.are_you_sure = "您的预订将被取消。确定要继续吗?"
        self.are_you_sure_2 = "确定要继续吗?"